#!/usr/bin/env python
# -*- coding: utf-8 -*-

from contour import Contour

data = {"marvin87:relating":
        [['< 5 0 2 3 1 4 >', 229, ['Figure 2',
                                   'Subsegs of cardinality 4']],
         ['< 5 0 2 3 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 3 0 1 2 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 0 2 3 1 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 5 3 1 4 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 3 1 0 2 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 5 0 4 0 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 3 0 1 2 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 0 3 2 4 1 >', 230, ['Comprasion Matrices ',
                                 'Normal Form / Translation ',
                                 'Figure 3']],
         ['< 0 4 2 3 1 >', 230, ['Comprasion Matrices ',
                                 'Figure 3']],
         ['< 0 5 4 7 3 >', 230, ['Comprasion Matrices',
                                 'Normal Form / Translation ',
                                 'Figure 3']],
         ['< 0 3 1 2 4 >', 230, ['Structure of the Comprasion Matrices',
                                 'Main Diagonal',
                                 'Figure 4']],
         ['< 0 2 1 4 3 5 >', 233, ['Equivalence classes',
                                   'Comparison matrix',
                                   'Operations',
                                   'Prime Form',
                                   'Figure 5']],
         ['< 1 2 0 4 3 5 >', 233, ['Equivalence classes',
                                   'Comparison matrix',
                                   'Operations',
                                   'Prime Form',
                                   'Figure 5']],
         ['< 0 4 3 4 1 2 >', 233, ['Equivalence classes',
                                   'Comparison matrix',
                                   'Operations',
                                   'Prime Form',
                                   'Figure 5']],
         ['< 4 5 2 3 0 1 >', 233, ['Equivalence classes',
                                   'Comparison matrix',
                                   'Operations',
                                   'Prime Form',
                                   'Comparisons Among Selected Csegs Where',
                                   'Figure 5']],
         ['< 0 1 3 2 >', 234, ['Comparison matrix',
                               'Operations']],
         ['< 0 1 3 2 >', 235, ['Comparison matrix',
                               'Operations',
                               'Csegs',
                               'Space Segment Class',
                               'Figure 6']],
         ['< 3 2 0 1 >', 235, ['Comparison matrix',
                               'Operations',
                               'Csegs',
                               'Space Segment Class',
                               'Figure 6']],
         ['< 1 0 2 3 >', 235, ['Comparison matrix',
                               'Operations',
                               'Csegs',
                               'Space Segment Class',
                               'Figure 6']],
         ['< 2 3 1 0 >', 235, ['Comparison matrix',
                               'Operations',
                               'Csegs',
                               'Space Segment Class',
                               'Figure 6']],
         ['< 0 3 1 2 >', 236, ['Prime Form Algorithm',
                               'Operations',
                               'Csegs',
                               'Figure 7']],
         ['< 3 0 2 1 >', 236, ['Prime Form Algorithm',
                               'Operations',
                               'Csegs',
                               'Figure 7']],
         ['< 1 2 0 4 >', 236, ['Prime Form Algorithm',
                               'Operations',
                               'Csegs',
                               'Figure 7']],
         ['< 3 2 4 1 >', 236, ['Prime Form Algorithm',
                               'Operations',
                               'Csegs',
                               'Figure 7']],
         ['< 1 2 0 3 >', 236, ['Prime Form Algorithm',
                               'Operations',
                               'Csegs',
                               'Figure 7']],
         ['< 2 1 3 0 >', 236, ['Prime Form Algorithm',
                               'Operations',
                               'Csegs',
                               'Figure 7']],
         ['< 0 2 3 1 >', 237, ['Similarity between two csegclasse']],
         ['< 3 1 0 2 >', 237, ['Similarity between two csegclasse']],
         ['< 4 8 2 3 6 1 >', 237, ['?']],
         ['< 2 0 1 3 >', 238, ['CSIM as Similarity Measurement for Csegs of the Same Cardinalit',
                               'Figure 8']],
         ['< 0 1 2 3 >', 238, ['CSIM as Similarity Measurement for Csegs of the Same Cardinalit',
                               'Figure 8']],
         ['< 1 3 0 2 >', 238, ['CSIM as Similarity Measurement for Csegs of the Same Cardinalit',
                               'Figure 8']],
         ['< 0 2 3 1 >', 238, ['CSIM as Similarity Measurement for Csegs of the Same Cardinalit',
                               'Figure 8']],
         ['< 0 2 3 1 >', 239, ['CSIM for C-Space Segment Classes',
                               'Figure 9']],
         ['< 3 1 0 2 >', 239, ['CSIM for C-Space Segment Classes',
                               'Figure 9']],
         ['< 2 0 1 3 >', 239, ['CSIM for C-Space Segment Classes',
                               'Figure 9']],
         ['< 1 3 2 0 >', 239, ['CSIM for C-Space Segment Classes',
                               'Figure 9']],
         ['< 1 0 4 3 2 >', 239, ['CSIM for C-Space Segment Classes',
                                 'Figure 9']],
         ['< 1 2 4 0 3 >', 239, ['CSIM for C-Space Segment Classes',
                                 'Figure 9']],
         ['< 3 2 0 4 1 >', 239, ['CSIM for C-Space Segment Classes',
                                 'Figure 9']],
         ['< 3 0 4 2 1 >', 239, ['CSIM for C-Space Segment Classes',
                                 'Figure 9']],
         ['< 1 4 0 2 3 >', 239, ['CSIM for C-Space Segment Classes',
                                 'Figure 9']],
         ['< 0 2 1 3 4 >', 240, ['Non-contiguous and contiguous subsets',
                                 '????????']],
         ['< 4 5 2 3 6 1 >', 241, ['CEMB (A,B)',
                                   'Figure 10']],
         ['< 0 2 1 3 4 >', 242, ['Matrix Embedding',
                                 'CEMB (A,B)',
                                 'Figure 11A']],
         ['< 0 2 1 3 4 >', 243, ['CEMB (A,B)',
                                 'Embedded Csubsegc by Translation',
                                 'Figure 11B']],
         ['< 1 0 4 3 2 >', 244, ['Subsegs',
                                 'Common Subsegs',
                                 'CMEM',
                                 'Figure 12']],
         ['< 2 0 1 4 3 >', 244, ['Subsegs',
                                 'Common Subsegs',
                                 'CMEM',
                                 'Figure 12']],
         ['< 0 5 3 2 4 1 >', 247, ['Consecutive Repeated Notes',
                                   'Figure 14']],
         ['< 0 5 3 3 2 4 1 >', 247, ['Consecutive Repeated Notes',
                                     'Figure 14']],
         ['< 1 2 3 0 3 1 >', 247, ['Non-Consecutive Repeated Notes',
                                   'Operations',
                                   'Figure 14']],
         ['< 2 1 0 3 0 2 >', 247, ['Non-Consecutive Repeated Notes',
                                   'Operations',
                                   'Figure 14']],
         ['< 1 3 0 3 2 1 >', 247, ['Non-Consecutive Repeated Notes',
                                   'Operations',
                                   'Figure 14']],
         ['< 2 0 3 0 1 2 >', 247, ['Non-Consecutive Repeated Notes',
                                   'Operations',
                                   'Figure 14']],
         ['< 5 0 2 3 1 4 >', 229, ['Figure 2',
                                   'Subsegs of cardinality 4']],
         ['< 5 0 2 3 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 3 0 1 2 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 0 2 3 1 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 5 3 1 4 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 3 1 0 2 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 5 0 4 0 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 3 0 1 2 >', 229, ['Subsegs of cardinality 4',
                               'Figure 2']],
         ['< 0 3 2 4 1 >', 230, ['Comprasion Matrices',
                                 'Normal Form / Translation ',
                                 'Figure 3']],
         ['< 0 4 2 3 1 >', 230, ['Comprasion Matrices',
                                 'Figure 3']],
         ['< 0 5 4 7 3 >', 230, ['Comprasion Matrices',
                                 'Normal Form / Translation ',
                                 'Figure 3']],
         ['< 0 3 1 2 4 >', 230, ['Structure of the Comprasion Matrices',
                                 'Main Diagonal',
                                 'Figure 4']],
         ['< 0 2 1 4 3 5 >', 233, ['Equivalence classes',
                                   'Comparison matrix',
                                   'Operations',
                                   'Prime Form',
                                   'Figure 5']],
         ['< 1 2 0 4 3 5 >', 233, ['Equivalence classes',
                                   'Comparison matrix',
                                   'Operations',
                                   'Prime Form',
                                   'Figure 5']],
         ['< 0 4 3 4 1 2 >', 233, ['Equivalence classes',
                                   'Comparison matrix',
                                   'Operations',
                                   'Prime Form',
                                   'Figure 5']],
         ['< 4 5 2 3 0 1 >', 233, ['Equivalence classes',
                                   'Comparison matrix',
                                   'Operations',
                                   'Prime Form',
                                   'Comparisons Among Selected Csegs Where',
                                   'Figure 5']],
         ['< 0 1 3 2 >', 234, ['Comparison matrix',
                               'Operations']],
         ['< 0 1 3 2 >', 235, ['Comparison matrix',
                               'Operations',
                               'Csegs',
                               'Space Segment Class',
                               'Figure 6']],
         ['< 3 2 0 1 >', 235, ['Comparison matrix',
                               'Operations',
                               'Csegs',
                               'Space Segment Class',
                               'Figure 6']],
         ['< 1 0 2 3 >', 235, ['Comparison matrix',
                               'Operations',
                               'Csegs',
                               'Space Segment Class',
                               'Figure 6']],
         ['< 2 3 1 0 >', 235, ['Comparison matrix',
                               'Operations',
                               'Csegs',
                               'Space Segment Class',
                               'Figure 6']],
         ['< 0 3 1 2 >', 236, ['Prime Form Algorithm',
                               'Operations',
                               'Csegs',
                               'Figure 7']],
         ['< 3 0 2 1 >', 236, ['Prime Form Algorithm',
                               'Operations', 'Csegs', 'Figure 7']],
         ['< 1 2 0 4 >', 236, ['Prime Form Algorithm',
                               'Operations',
                               'Csegs',
                               'Figure 7']],
         ['< 3 2 4 1 >', 236, ['Prime Form Algorithm',
                               'Operations',
                               'Csegs',
                               'Figure 7']],
         ['< 1 2 0 3 >', 236, ['Prime Form Algorithm',
                               'Operations',
                               'Csegs',
                               'Figure 7']],
         ['< 2 1 3 0 >', 236, ['Prime Form Algorithm',
                               'Operations',
                               'Csegs',
                               'Figure 7']],
         ['< 0 2 3 1 >', 237, ['Similarity between two csegclasse']],
         ['< 3 1 0 2 >', 237, ['Similarity between two csegclasse']],
         ['< 4 8 2 3 6 1 >', 237, ['?']],
         ['< 2 0 1 3 >', 238, ['CSIM as Similarity Measurement for Csegs of the Same Cardinalit',
                               'Figure 8']],
         ['< 0 1 2 3 >', 238, ['CSIM as Similarity Measurement for Csegs of the Same Cardinalit',
                               'Figure 8']],
         ['< 1 3 0 2 >', 238, ['CSIM as Similarity Measurement for Csegs of the Same Cardinalit',
                               'Figure 8']],
         ['< 0 2 3 1 >', 238, ['CSIM as Similarity Measurement for Csegs of the Same Cardinalit',
                               'Figure 8']],
         ['< 0 2 3 1 >', 239, ['CSIM for C-Space Segment Classes',
                               'Figure 9']],
         ['< 3 1 0 2 >', 239, ['CSIM for C-Space Segment Classes',
                               'Figure 9']],
         ['< 2 0 1 3 >', 239, ['CSIM for C-Space Segment Classes',
                               'Figure 9']],
         ['< 1 3 2 0 >', 239, ['CSIM for C-Space Segment Classes',
                               'Figure 9']],
         ['< 1 0 4 3 2 >', 239, ['CSIM for C-Space Segment Classes',
                                 'Figure 9']],
                            ['< 1 2 4 0 3 >', 239, ['CSIM for C-Space Segment Classes',
                                                    'Figure 9']],
         ['< 3 2 0 4 1 >', 239, ['CSIM for C-Space Segment Classes',
                                 'Figure 9']],
         ['< 3 0 4 2 1 >', 239, ['CSIM for C-Space Segment Classes',
                                 'Figure 9']],
         ['< 1 4 0 2 3 >', 239, ['CSIM for C-Space Segment Classes',
                                 'Figure 9']],
         ['< 0 2 1 3 4 >', 240, ['Non-contiguous and contiguous subsets',
                                 '?']],
         ['< 4 5 2 3 6 1 >', 241, ['CEMB (A,B)',
                                   'Figure 10']],
         ['< 0 2 1 3 4 >', 242, ['Matrix Embedding',
                                 'CEMB (A,B)',
                                 'Figure 11A']],
         ['< 0 2 1 3 4 >', 243, ['CEMB (A,B)',
                                 'Embedded Csubsegc by Translation',
                                 'Figure 11B']],
         ['< 1 0 4 3 2 >', 244, ['Subsegs',
                                 'Common Subsegs',
                                 'CMEM',
                                 'Figure 12']],
         ['< 2 0 1 4 3 >', 244, ['Subsegs',
                                 'Common Subsegs',
                                 'CMEM',
                                 'Figure 12']],
         ['< 0 5 3 2 4 1 >', 247, ['Consecutive Repeated Notes',
                                   'Figure 14']],
         ['< 0 5 3 3 2 4 1 >', 247, ['Consecutive Repeated Notes',
                                     'Figure 14']],
         ['< 1 2 3 0 3 1 >', 247, ['Non-Consecutive Repeated Notes',
                                   'Operations',
                                   'Figure 14']],
         ['< 2 1 0 3 0 2 >', 247, ['Non-Consecutive Repeated Notes',
                                   'Operations',
                                   'Figure 14']],
         ['< 1 3 0 3 2 1 >', 247, ['Non-Consecutive Repeated Notes',
                                   'Operations',
                                   'Figure 14']],
         ['< 2 0 3 0 1 2 >', 247, ['Non-Consecutive Repeated Notes',
                                   'Operations',
                                   'Figure 14']]]
        }
